language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  
matrix:
  allow_failures: []

before_script:
  - if [[ "$TRAVIS_PHP_VERSION" = "hhvm" ]]; then mkdir -p /home/travis/.phpenv/versions/hhvm/etc/conf.d; fi;
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script: phpunit --coverage-clover=coverage.clover

after_script:
    - if [ "$TRAVIS_PHP_VERSION" = "5.5" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi;
    - if [ "$TRAVIS_PHP_VERSION" = "5.5" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi;
